### ISSUE TITLE
java.lang.NoSuchFieldError: View from the IntelliJ's Exception Tracker

### ISSUE THREAD

**Issue by ignatov** [Haehnchen/idea-android-studio-plugin#14]
View

java.lang.NoSuchFieldError: View
	at de.espend.idea.android.linemarker.ViewInflateLineMarker.attachLineIcon(ViewInflateLineMarker.java:84)
	at de.espend.idea.android.linemarker.ViewInflateLineMarker.attachFindViewByIdInflate(ViewInflateLineMarker.java:42)
	at de.espend.idea.android.linemarker.ViewInflateLineMarker.collectSlowLineMarkers(ViewInflateLineMarker.java:33)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.queryProviders(LineMarkersPass.java:209)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.lambda$doCollectInformation$3(LineMarkersPass.java:116)
	at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutsideInOneRoot(Divider.java:80)
	at com.intellij.codeInsight.daemon.impl.LineMarkersPass.doCollectInformation(LineMarkersPass.java:103)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:437)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1137)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:430)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:429)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:405)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by serejke** [comment]
Due to this binary [incompatibility](https://github.com/Haehnchen/idea-android-studio-plugin/blob/65b9b4bd8873a44eb906c7fd879d7603b0e4ec4c/src/de/espend/idea/android/linemarker/ViewInflateLineMarker.java#L84)
your plugin's "until-build" value has been reduced to 191.5000.

Please see detailed verification results on https://plugins.jetbrains.com/plugin/7405-android-studio-prettify/update/19209.

You may re-upload the plugin with compatibility restored.
Thanks!
