### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException:

### ISSUE THREAD

**Issue by cikichen** [Haehnchen/idea-android-studio-plugin#3]
```
java.lang.ArrayIndexOutOfBoundsException: 1
    at de.espend.idea.android.AndroidView.<init>(AndroidView.java:20)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:109)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
    at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:90)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:55)
    at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
    at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
    at de.espend.idea.android.utils.AndroidUtils.getIDsFromXML(AndroidUtils.java:95)
    at de.espend.idea.android.utils.AndroidUtils.getViewType(AndroidUtils.java:123)
    at de.espend.idea.android.utils.AndroidViewUtil.getAndroidView(AndroidViewUtil.java:92)
    at de.espend.idea.android.linemarker.ViewInflateLineMarker.attachFindViewByIdInflate(ViewInflateLineMarker.java:40)
    at de.espend.idea.android.linemarker.ViewInflateLineMarker.collectSlowLineMarkers(ViewInflateLineMarker.java:33)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1103)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)



java.lang.ArrayIndexOutOfBoundsException: 1
    at de.espend.idea.android.AndroidView.<init>(AndroidView.java:20)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:109)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlTag(XmlElementVisitor.java:54)
    at com.intellij.psi.impl.source.xml.XmlTagImpl.accept(XmlTagImpl.java:1017)
    at com.intellij.psi.impl.source.tree.CompositePsiElement.acceptChildren(CompositePsiElement.java:80)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.XmlElementVisitor.visitXmlElement(XmlElementVisitor.java:22)
    at com.intellij.psi.XmlElementVisitor.visitXmlDocument(XmlElementVisitor.java:42)
    at com.intellij.psi.impl.source.xml.XmlDocumentImpl.accept(XmlDocumentImpl.java:90)
    at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:196)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:779)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitElement(XmlRecursiveElementVisitor.java:37)
    at de.espend.idea.android.utils.AndroidUtils$1.visitElement(AndroidUtils.java:98)
    at com.intellij.psi.PsiElementVisitor.visitFile(PsiElementVisitor.java:34)
    at com.intellij.psi.XmlRecursiveElementVisitor.visitFile(XmlRecursiveElementVisitor.java:55)
    at com.intellij.psi.XmlElementVisitor.visitXmlFile(XmlElementVisitor.java:26)
    at com.intellij.psi.impl.source.xml.XmlFileImpl.accept(XmlFileImpl.java:71)
    at de.espend.idea.android.utils.AndroidUtils.getIDsFromXML(AndroidUtils.java:95)
    at de.espend.idea.android.utils.AndroidUtils.getViewType(AndroidUtils.java:123)
    at de.espend.idea.android.utils.AndroidViewUtil.getAndroidView(AndroidViewUtil.java:92)
    at de.espend.idea.android.linemarker.ViewInflateLineMarker.attachFindViewByIdInflate(ViewInflateLineMarker.java:40)
    at de.espend.idea.android.linemarker.ViewInflateLineMarker.collectSlowLineMarkers(ViewInflateLineMarker.java:33)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.addLineMarkers(SlowLineMarkersPass.java:78)
    at com.intellij.codeInsight.daemon.impl.SlowLineMarkersPass.doCollectInformation(SlowLineMarkersPass.java:65)
    at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1103)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:452)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:432)
    at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
    at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

```

**Comment by NermineMunla** [comment]
http://envyandroid.com/arrayindexoutofboundsexception-listadapter/
